[toolchain]
channel = "stable"
components = ["rustc", "cargo", "rustfmt", "clippy", "rust-src", "llvm-tools-preview"]

profile = "minimal"

targets = ["x86_64-unknown-linux-gnu"]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
  "-C", "link-arg=-fuse-ld=bfd", 
  "-C", "relocation-model=pic",
  "-C", "codegen-units=1"
]
